Store major/minor version instead of "schema version"
Particular/NServiceBus.Persistence.CosmosDB pull request #72
Opened 2020-10-09 15:42 UTC by boblangley

This is an alternative to #71 which hard codes a "schema version" to `0.1.0`

Instead, use `GitVersionInformation` to store the Major and Minor version in the metadata. They are stored as separate values to make querying easier since there is no easy way to write a greater than/less than WHERE statements for dot notation version information.

This also removes the need for shared files since both the export tool and the persister both generate `GitVersionInformation`.

The downside to this approach is the reliance on the `GitVersion` package at runtime, but I do not think this is an overwhelming negative.

2020-10-09 16:32 UTC, SeanFeldman approved these changes

2020-10-09 21:58 UTC, danielmarbach commented
I think I highlighted this in the discussions before internally but happy to repeat the decision we took for RavenDB. The schema version cannot be bound to the git version because it would mean version changes of the assembly would lead to updates of the docs schema even though the actual schema hasn't changed. The consequence of that is when you upgrade all loaded sagas and records would be changed to a new schema. The hard coded version makes sense in because only when a real breaking change of the storage schema is introduced then the version needs to be bumped deliberately and not due to manor or major version bumps of the assembly. Essentially the minor and major version of the assembly are primarily an indication of semantic changes to the public Api and those are independent from schema changes.

2020-10-09 21:59 UTC, danielmarbach requested changes
See comment above

2020-10-13 02:40 UTC, boblangley commented
We are withdrawing this change for now. We can revisit this decision for a later release.

2020-10-13 02:40 UTC, closed without merging